### ISSUE TITLE
TC Supply - ShowKontrol

### ISSUE THREAD

**Issue by PouleR** [brunchboy/beat-link#14]
Interesting stuff happing, see:

https://djworx.com/pioneer-dj-gets-light-shows-showkontrol/

and

https://www.tc-supply.com

**Comment by brunchboy** [comment]
I saw that, it seems they are using some new protocols supported only in the latest hardware (nxs2, tour). Hopefully someone with access to such hardware (which presently excludes me) will be able to analyze this new protocol, contribute their knowledge to the dysentery project, and see if there is anything we can use. It would be nice, for example, with such hardware not to need to worry about caching metadata when you have four players on the network.

**Comment by eiglive** [comment]
Interesting it is. Please note that you break EiG's EULA by hacking and that makes you eligble to be brought to court. As we work on api'swe encourage you to be patient.

**Comment by brunchboy** [comment]
What a strange and hostile comment. I’ve never been party to any license agreements; I’ve never been a user of or looked at any EiG software. These projects are the results of years of research by smart, resourceful and friendly people around the world. We’ve shared all the details and results of our discoveries every step of the way, as can be seen from the historical record in the repositories, and multiple successful projects in many languages have resulted. We will continue in these beneficial open source efforts for experimenters and developers everywhere.

**Comment by eiglive** [comment]
You should not see this as a hostile comment, but just a proper warning that reverse engineering ShowKontrol protocols is prohibited. You ask people to look into this and by doing so you ask people to break our EULA. Publishing protocols that are protected, in public is illegal and protected by US laws.

**Comment by PouleR** [comment]
Pioneer just introduced a new product: https://www.youtube.com/watch?v=_ks7YNG4DRs

Pioneer DJ RB-DMX1

**Comment by brunchboy** [comment]
Yes, @PouleR I just got email from @EvanPurkhiser about that. Very interesting, I bet they will capture a lot of the casual and lower-end shows with that, it looks quite interesting and fun and easy. But I doubt it will have the kind of openness that will satisfy people doing the sorts of complex and custom integrations we’ve been building support for.
